### ISSUE TITLE
Scaling up PSU

### ISSUE THREAD

**Issue by jjafuller** [letsRTFM/AI-Workstation#1]
I love the build. I have been reviewing various configurations for my dual 3090s and I think I like this one the best. As listed my only real concern is the PSU. Do you still scaling up to something like the NZXT C1200 Gold would give enough headroom for it to run comfortably?

**Comment by mattbucci** [comment]
As is I don't think I'm coming close to the 1000W limit, each GPU pulls about 300W, I never saw more than 880W as measured at the wall under load, I would only be worried about it if you were trying to put 4000 or 5000 series cards into this setup.

That said the geometric future will accommodate whatever you want to throw at it, happy to attach pictures if you need any, there's no reason at all I'm using an SFXL here except that i do a lot of smaller builds and I try to standardize the parts I need for reuse, if you can find a power supply you like better I don't think there should be any issue.

I had considered the NZXT 1500W platinum https://a.co/d/cnWCSil (non affiliate link)
https://amzn.to/3AqubM2 (Affiliate link)
but I hadn't tested it personally.

I think that would give enough headroom for up to dual 4090s.

On a personal note I think sub 1000W for a workstation is a good target considering home circuits and other potential issues.

**Comment by jjafuller** [comment]
That is a good call. I am considering upgrading to 40 series at some point in the future if their prices softer after the series 50 release. However, before doing that I need to get the electrician out to add another 20-amp circuit to my server room.

**Comment by mattbucci** [comment]
5090 32GB seems to be the only card worth grabbing in the new gen but the power usage is absurd.

If the 4090 comes down in price to sub $1000 that would probably be my recommendation 

a 24GB 5080 TI may also be an interesting choice but it will be some years and may still be cost prohibitive.

I’ve also benchmarked this system against a $3k m4 Mac mini and the dual 3090s are about 4x the performance on llama 70B. I wish there were more competitive options but at this time this is close to optimal

**Comment by jjafuller** [comment]
Yeah. It has a great value to performance ratio. I have been toying with the idea of adding a third card via an m.2 to pcie adapter. It would only be an x4, but it would be really nice to have a larger context window when running llama 3.3 70b.

**Comment by mattbucci** [comment]
I’m running a 10gig nic in my extra nvme slot, but I’ll admit I don’t do much with it yet.
